In [1]:
import pandas as pd 
import seaborn as sns 
import plotly.express as px

ri = pd.read_csv("Rental_income_citywide.csv")
ri

/tmp/ipykernel_8625/3242206985.py:5: DtypeWarning: Columns (0: Total Units 1, 1: Total Units 2, 2: Total Units 3, 3: Expense per SqFt 3) have mixed types. Specify dtype option on import or set low_memory=False.
  ri = pd.read_csv("Rental_income_citywide.csv")

,Boro-Block-Lot,Address,Neighborhood,Building Classification,Total Units,Year Built,Gross SqFt,Estimated Gross Income,Gross Income per SqFt,Estimated Expense,...,Gross SqFt 3,Estimated Gross Income 3,Gross Income per SqFt 3,Estimated Expense 3,Expense per SqFt 3,Net Operating Income 3,Full Market Value 3,Market Value per SqFt 3,Distance from Co-op in miles 2,Report Year
0,1-00011-0014,26 BEAVER STREET,FINANCIAL,D4 -ELEVATOR,21,1909,"51,387","2,399,773",46.70,"940,382",...,"335,746","15,679,338",46.70,"6,144,152",18.3,"9,535,186","71,229,000",212.15,0.21,2019
1,1-00028-0001,3 HANOVER SQUARE,FINANCIAL,D0 -ELEVATOR,211,1926,"239,121","9,462,018",39.57,"2,907,711",...,"473,460","18,706,405",39.51,"6,538,483",13.81,"12,167,922","145,268,000",306.82,0.10,2019
2,1-00094-0001,80 GOLD STREET,SOUTHBRIDGE,D4 -ELEVATOR,"1,652",1971,"2,155,492","68,113,547",31.60,"27,676,517",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019
3,1-00100-0026,138 NASSAU STREET,SOUTHBRIDGE,D4 -ELEVATOR,43,1901,"79,422","3,130,815",39.42,"882,378",...,"31,715","1,205,170",38.00,"319,370",10.07,"885,800","10,485,000",330.60,0.27,2019
4,1-00117-0001,185 PARK ROW,CIVIC CENTER,D4 -ELEVATOR,465,1960,"515,425","25,889,798",50.23,"10,354,888",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49255,5-02925-0432,361 SKYLINE DRIVE,CONCORD-FOX HILLS,C6 -WALK-UP,11,1999,"21,780","504,425",23.16,"207,346",...,"9,750","225,810",23.16,"92,820",9.52,"132,990","994,000",101.95,1.00,2022
49256,5-02925-0450,295 SKYLINE DRIVE,CONCORD-FOX HILLS,C6 -WALK-UP,11,2000,"21,865","506,393",23.16,"208,155",...,"9,750","225,810",23.16,"92,820",9.52,"132,990","994,000",101.95,1.00,2022
49257,5-02925-0479,46 CIRCLE LOOP,CONCORD-FOX HILLS,C6 -WALK-UP,19,2000,"37,220","777,898",20.90,"386,344",...,"19,386","405,167",20.90,"201,227",10.38,"203,941","1,879,000",96.93,0.50,2022
49258,5-04640-0022,3745 AMBOY ROAD,GREAT KILLS,C6 -WALK-UP,36,1974,"26,490","508,343",19.19,"228,079",...,"10,200","199,002",19.51,"88,536",8.68,"110,466","844,000",82.75,2.51,2022
49259,5-05229-0007,475 ARMSTRONG AVENUE,GREAT KILLS,C6 -WALK-UP,60,1974,"38,647","828,978",21.45,"468,788",...,"10,000","204,700",20.47,"111,400",11.14,"93,300","538,000",53.80,2.03,2022

In [2]:
ri.info()

<class 'pandas.DataFrame'>
RangeIndex: 49260 entries, 0 to 49259
Data columns (total 60 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Boro-Block-Lot                  49260 non-null  str
 1   Address                         49260 non-null  str
 2   Neighborhood                    49260 non-null  str
 3   Building Classification         49260 non-null  str
 4   Total Units                     49260 non-null  str
 5   Year Built                      49260 non-null  int64
 6   Gross SqFt                      49260 non-null  str
 7   Estimated Gross Income          49260 non-null  str
 8   Gross Income per SqFt           49260 non-null  float64
 9   Estimated Expense               49260 non-null  str
 10  Expense per SqFt                49260 non-null  float64
 11  Net Operating Income            49260 non-null  str
 12  Full Market Value               49260 non-null  str
 13  Market Value per SqFt           49260 non-null  float64
 14  Boro-Block-Lot 1                49260 non-null  str
 15  Address 1                       49260 non-null  str
 16  Neighborhood 1                  49260 non-null  str
 17  Building Classification 1       49260 non-null  str
 18  Total Units 1                   49260 non-null  object
 19  Year Built 1                    49260 non-null  int64
 20  Gross SqFt 1                    49260 non-null  str
 21  Estimated Gross Income 1        49259 non-null  str
 22  Gross Income per SqFt 1         49260 non-null  float64
 23  Estimated Expense 1             49259 non-null  str
 24  Expense per SqFt 1              49260 non-null  float64
 25  Net Operating Income 1          49257 non-null  str
 26  Full Market Value 1             49260 non-null  str
 27  Market Value per SqFt 1         49260 non-null  float64
 28  Distance from Co-op in miles    49259 non-null  float64
 29  Boro-Block-Lot 2                49009 non-null  str
 30  Address 2                       49009 non-null  str
 31  Neighborhood 2                  49009 non-null  str
 32  Building Classification 2       49009 non-null  str
 33  Total Units 2                   49009 non-null  object
 34  Year Built 2                    49009 non-null  float64
 35  Gross SqFt 2                    49009 non-null  str
 36  Estimated Gross Income 2        49009 non-null  str
 37  Gross Income per SqFt 2         49009 non-null  float64
 38  Estimated Expense 2             49009 non-null  str
 39  Expense per SqFt 2              49009 non-null  float64
 40  Net Operating Income 2          49005 non-null  str
 41  Full Market Value 2             49009 non-null  str
 42  Market Value per SqFt 2         49009 non-null  float64
 43  Distance from Co-op in miles 1  49007 non-null  float64
 44  Boro-Block-Lot 3                40027 non-null  str
 45  Address 3                       40027 non-null  str
 46  Neighborhood 3                  40027 non-null  str
 47  Building Classification 3       40027 non-null  str
 48  Total Units 3                   40027 non-null  object
 49  Year Built 3                    40027 non-null  float64
 50  Gross SqFt 3                    40027 non-null  str
 51  Estimated Gross Income 3        40027 non-null  str
 52  Gross Income per SqFt 3         40027 non-null  float64
 53  Estimated Expense 3             40026 non-null  str
 54  Expense per SqFt 3              40026 non-null  object
 55  Net Operating Income 3          40023 non-null  str
 56  Full Market Value 3             40027 non-null  str
 57  Market Value per SqFt 3         40027 non-null  float64
 58  Distance from Co-op in miles 2  40027 non-null  float64
 59  Report Year                     49260 non-null  int64
dtypes: float64(16), int64(3), object(4), str(37)
memory usage: 22.5+ MB

In [3]:

print(ri['Neighborhood'].unique())

<StringArray>
[              'FINANCIAL',             'SOUTHBRIDGE',
            'CIVIC CENTER',                 'TRIBECA',
               'CHINATOWN',                    'SOHO',
         'LOWER EAST SIDE',           'ALPHABET CITY',
            'EAST VILLAGE',               'BAY RIDGE',
 ...
            'DONGAN HILLS',              'GRANT CITY',
             'GREAT KILLS', 'GREAT KILLS-BAY TERRACE',
             'CITY ISLAND',         'CARROLL GARDENS',
                'RED HOOK',        'ROOSEVELT ISLAND',
            'NEW BRIGHTON',       'WEST NEW BRIGHTON']
Length: 297, dtype: str

In [4]:
ri['Neighborhood'].value_counts()

Neighborhood
UPPER EAST SIDE (79-96)     3181
UPPER EAST SIDE (59-79)     2355
UPPER WEST SIDE (79-96)     1679
CHELSEA                     1245
JACKSON HEIGHTS             1218
                            ...
SO. JAMAICA-BAISLEY PARK       1
ARROCHAR-SHORE ACRES           1
DONGAN HILLS                   1
GREAT KILLS-BAY TERRACE        1
NEW BRIGHTON                   1
Name: count, Length: 297, dtype: int64

In [5]:
target_neighborhoods = ['MOTT HAVEN/PORT MORRIS', 'HUNTS POINT', 'MORRISANIA/LONGWOOD', 'CROTONA PARK']
filtered_neighborhoods = ri[ri['Neighborhood'].isin(target_neighborhoods)]
filtered_neighborhoods.sample(5)

,Boro-Block-Lot,Address,Neighborhood,Building Classification,Total Units,Year Built,Gross SqFt,Estimated Gross Income,Gross Income per SqFt,Estimated Expense,...,Gross SqFt 3,Estimated Gross Income 3,Gross Income per SqFt 3,Estimated Expense 3,Expense per SqFt 3,Net Operating Income 3,Full Market Value 3,Market Value per SqFt 3,Distance from Co-op in miles 2,Report Year
34222,2-02603-0024,590 SOUTHERN BOULEVARD,MORRISANIA/LONGWOOD,C6-WALK-UP,29,1924,"26,742","310,742",11.62,"199,495",...,"39,035","453,587",11.62,"291,201",7.46,"162,386","1,430,000",36.63,0.14,2016
29798,2-02293-0041,426 EAST 149 STREET,MOTT HAVEN/PORT MORRIS,C6-WALK-UP,11,1905,"10,845","134,370",12.39,"74,397",...,"10,490","129,971",12.39,"71,961",6.86,"58,010","302,000",28.79,1.11,2015
16200,2-02698-0063,941 ROGERS PLACE,MORRISANIA/LONGWOOD,C6-WALK-UP,20,1925,"16,950","193,061",11.39,"106,277",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012
16196,2-02683-0100,1021 AVENUE ST JOHN,MORRISANIA/LONGWOOD,C6-WALK-UP,79,1925,"61,878","479,555",7.75,"233,280",...,"62,060","423,978",6.83,"245,907",3.96,"178,071","1,029,000",16.58,1.08,2012
43039,2-02608-0019,1109 FRANKLIN AVENUE,MORRISANIA/LONGWOOD,C6 -WALK-UP,25,1917,"24,750","300,713",12.15,"166,568",...,"16,086","177,589",11.04,"106,972",6.65,"70,617","348,000",21.63,0.10,2018

In [6]:
filtered_columns = filtered_neighborhoods[['Neighborhood', 'Building Classification', 'Total Units', 'Year Built', 'Estimated Gross Income', 'Estimated Expense']]
filtered_columns

,Neighborhood,Building Classification,Total Units,Year Built,Estimated Gross Income,Estimated Expense
2324,MOTT HAVEN/PORT MORRIS,C6 -WALK-UP,11,1905,"199,440","112,463"
2325,MOTT HAVEN/PORT MORRIS,C6 -WALK-UP,11,1931,"162,409","90,478"
2326,MORRISANIA/LONGWOOD,C6 -WALK-UP,46,1928,"621,062","370,142"
2327,MORRISANIA/LONGWOOD,C6 -WALK-UP,15,1920,"202,289","115,757"
2328,MORRISANIA/LONGWOOD,C6 -WALK-UP,25,1912,"241,941","141,376"
...,...,...,...,...,...,...
47331,MORRISANIA/LONGWOOD,C6 -WALK-UP,16,1904,"249,075","144,956"
47332,MORRISANIA/LONGWOOD,C6 -WALK-UP,16,1904,"197,197","99,242"
47333,MORRISANIA/LONGWOOD,C6 -WALK-UP,16,1904,"197,197","99,242"
47334,MORRISANIA/LONGWOOD,C6 -WALK-UP,25,1930,"385,358","215,073"
47338,MORRISANIA/LONGWOOD,C6 -WALK-UP,73,1931,"1,168,322","636,914"

In [14]:
filtered_columns['Neighborhood'].value_counts()

Neighborhood
MORRISANIA/LONGWOOD       485
CROTONA PARK               50
HUNTS POINT                35
MOTT HAVEN/PORT MORRIS     33
Name: count, dtype: int64

In [7]:
filtered_neighborhoods1 = ri[ri['Neighborhood 1'].isin(target_neighborhoods)]
filtered_neighborhoods1.sample(5)

,Boro-Block-Lot,Address,Neighborhood,Building Classification,Total Units,Year Built,Gross SqFt,Estimated Gross Income,Gross Income per SqFt,Estimated Expense,...,Gross SqFt 3,Estimated Gross Income 3,Gross Income per SqFt 3,Estimated Expense 3,Expense per SqFt 3,Net Operating Income 3,Full Market Value 3,Market Value per SqFt 3,Distance from Co-op in miles 2,Report Year
2394,2-02720-0041,1025 LEGGETT AVENUE,MORRISANIA/LONGWOOD,C6 -WALK-UP,56,1924,"41,010","885,816",21.60,"358,838",...,"39,035","817,783",20.95,"325,942",8.35,"491,841","1,975,000",50.60,0.13,2019
25726,2-02421-0013,270 EAST 162 STREET,MELROSE/CONCOURSE,C6-WALK-UP,11,1931,"10,675","119,954",11.24,"79,114",...,"10,829","121,684",11.24,"80,255",7.41,"41,429","468,000",43.22,0.52,2014
11318,2-02698-0063,941 ROGERS PLACE,MORRISANIA/LONGWOOD,C6 -WALK-UP,20,1925,"16,950","274,590",16.20,"166,619",...,"11,360","198,346",17.46,"118,598",10.44,"79,747","604,000",53.17,0.73,2021
43054,2-02707-0030,715 FOX STREET,MORRISANIA/LONGWOOD,D4 -ELEVATOR,50,2008,"60,373","815,036",13.50,"405,707",...,"38,370","514,542",13.41,"305,425",7.96,"209,117","1,366,000",35.60,0.39,2018
47272,2-02683-0052,547 SOUTHERN BOULEVARD,MORRISANIA/LONGWOOD,C6 -WALK-UP,19,1906,"16,875","285,525",16.92,"157,106",...,"11,960","203,320",17.00,"102,497",8.57,"100,823","428,000",35.79,0.92,2022

In [8]:
filtered_columns1 = filtered_neighborhoods1[['Neighborhood 1', 'Building Classification 1', 'Total Units 1', 'Year Built 1', 'Estimated Gross Income 1', 'Estimated Expense 1']]
filtered_columns1

,Neighborhood 1,Building Classification 1,Total Units 1,Year Built 1,Estimated Gross Income 1,Estimated Expense 1
967,MORRISANIA/LONGWOOD,C7 -WALK-UP,15,1905,"141,368","75,253"
2324,MOTT HAVEN/PORT MORRIS,C7 -WALK-UP,55,1927,"1,009,893","559,393"
2325,MOTT HAVEN/PORT MORRIS,C7 -WALK-UP,49,1926,"744,062","414,518"
2326,MORRISANIA/LONGWOOD,C7 -WALK-UP,22,1907,"220,710","131,343"
2327,MORRISANIA/LONGWOOD,C7 -WALK-UP,19,1925,"178,656","102,776"
...,...,...,...,...,...,...
47332,MORRISANIA/LONGWOOD,C1 -WALK-UP,16,1911,"190,567","104,120"
47333,MORRISANIA/LONGWOOD,C1 -WALK-UP,16,1911,"190,567","104,120"
47334,MORRISANIA/LONGWOOD,C1 -WALK-UP,16,1904,"205,473","100,464"
47338,MORRISANIA/LONGWOOD,C1 -WALK-UP,15,1901,"303,367","151,683"
47463,MORRISANIA/LONGWOOD,D5 -ELEVATOR,42,1910,"579,729","241,032"

In [9]:
filtered_columns1['Neighborhood 1'].value_counts()

Neighborhood 1
MORRISANIA/LONGWOOD       503
CROTONA PARK               78
HUNTS POINT                32
MOTT HAVEN/PORT MORRIS     26
Name: count, dtype: int64

In [10]:
filtered_neighborhoods2 = ri[ri['Neighborhood 2'].isin(target_neighborhoods)]
filtered_neighborhoods2.sample(5)

,Boro-Block-Lot,Address,Neighborhood,Building Classification,Total Units,Year Built,Gross SqFt,Estimated Gross Income,Gross Income per SqFt,Estimated Expense,...,Gross SqFt 3,Estimated Gross Income 3,Gross Income per SqFt 3,Estimated Expense 3,Expense per SqFt 3,Net Operating Income 3,Full Market Value 3,Market Value per SqFt 3,Distance from Co-op in miles 2,Report Year
43005,2-02452-0029,1113 GRANT AVENUE,MELROSE/CONCOURSE,C6 -WALK-UP,70,1926,"57,080","743,752",13.03,"409,834",...,"66,400","865,192",13.03,"476,752",7.18,"388,440","2,453,000",36.94,0.67,2018
16243,2-02967-0006,1574 BOSTON ROAD,CROTONA PARK,D4-ELEVATOR,54,1929,"50,000","646,500",12.93,"398,500",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012
6873,2-02967-0006,1574 BOSTON ROAD,CROTONA PARK,D4 -ELEVATOR,54,1929,"50,000","967,000",19.34,"503,000",...,"74,990","1,382,066",18.43,"738,652",9.85,"643,414","4,588,000",61.18,0.64,2020
34436,2-03740-0005,1521 WATSON AVENUE,SOUNDVIEW,D4-ELEVATOR,63,1928,"62,916","1,104,805",17.56,"660,618",...,"83,481","1,051,026",12.59,"443,284",5.31,"607,742","4,086,000",48.95,0.66,2016
2371,2-02582-0061,823 EAST 147 STREET,MOTT HAVEN/PORT MORRIS,C6 -WALK-UP,38,1920,"25,980","404,249",15.56,"237,977",...,"43,134","671,165",15.56,"395,107",9.16,"276,058","1,065,000",24.69,0.73,2019

In [11]:
filtered_columns2 = filtered_neighborhoods2[['Neighborhood 2', 'Building Classification 2', 'Total Units 2', 'Year Built 2', 'Estimated Gross Income 2', 'Estimated Expense 2']]
filtered_columns2

,Neighborhood 2,Building Classification 2,Total Units 2,Year Built 2,Estimated Gross Income 2,Estimated Expense 2
241,MORRISANIA/LONGWOOD,C1 -WALK-UP,25,1906.0,"236,147","123,990"
967,MORRISANIA/LONGWOOD,C7 -WALK-UP,14,1882.0,"173,589","109,265"
2324,MOTT HAVEN/PORT MORRIS,C7 -WALK-UP,84,1925.0,"1,404,594","785,054"
2325,MOTT HAVEN/PORT MORRIS,C7 -WALK-UP,55,1927.0,"947,431","517,383"
2326,MORRISANIA/LONGWOOD,C7 -WALK-UP,18,1907.0,"196,224","116,946"
...,...,...,...,...,...,...
47453,MORRISANIA/LONGWOOD,D1 -ELEVATOR,63,1919.0,"807,462","492,491"
47454,MORRISANIA/LONGWOOD,D1 -ELEVATOR,63,1919.0,"807,462","492,491"
47455,MORRISANIA/LONGWOOD,D1 -ELEVATOR,63,1919.0,"807,462","492,491"
47456,MORRISANIA/LONGWOOD,D1 -ELEVATOR,63,1919.0,"807,462","492,491"
47457,MORRISANIA/LONGWOOD,D1 -ELEVATOR,63,1919.0,"752,178","492,491"

In [15]:
filtered_columns2['Neighborhood 2'].value_counts()

Neighborhood 2
MORRISANIA/LONGWOOD       545
CROTONA PARK               64
MOTT HAVEN/PORT MORRIS     39
HUNTS POINT                33
Name: count, dtype: int64

In [12]:
filtered_neighborhoods3 = ri[ri['Neighborhood 3'].isin(target_neighborhoods)]
filtered_neighborhoods3.sample(5)

,Boro-Block-Lot,Address,Neighborhood,Building Classification,Total Units,Year Built,Gross SqFt,Estimated Gross Income,Gross Income per SqFt,Estimated Expense,...,Gross SqFt 3,Estimated Gross Income 3,Gross Income per SqFt 3,Estimated Expense 3,Expense per SqFt 3,Net Operating Income 3,Full Market Value 3,Market Value per SqFt 3,Distance from Co-op in miles 2,Report Year
25770,2-02627-0005,902 EAGLE AVENUE,MORRISANIA/LONGWOOD,C6-WALK-UP,25,1914,"21,295","219,147",10.29,"130,286",...,"5,732","57,859",10.09,"34,173",5.96,"23,686","189,000",32.97,0.50,2014
2408,2-02763-0227,750 FAILE STREET,HUNTS POINT,D4 -ELEVATOR,111,1965,"108,306","1,692,823",15.63,"995,332",...,"31,385","502,474",16.01,"284,976",9.08,"217,498","1,369,000",43.62,0.10,2019
43067,2-02740-0071,874 MANIDA STREET,HUNTS POINT,C6 -WALK-UP,19,1910,"14,880","229,747",15.44,"138,086",...,"18,000","277,920",15.44,"167,040",9.28,"110,880","634,000",35.22,0.06,2018
25783,2-02711-0021,921 TIFFANY STREET,MORRISANIA/LONGWOOD,C6-WALK-UP,18,1989,"14,000","160,835",11.49,"80,918",...,"22,550","259,059",11.49,"130,336",5.78,"128,723","375,000",16.63,0.44,2014
16213,2-02727-0039,1111 SOUTHERN BOULEVARD,MORRISANIA/LONGWOOD,C6-WALK-UP,26,1925,"21,917","169,857",7.75,"90,079",...,"20,750","158,694",7.65,"103,151",4.97,"55,543","311,000",14.99,0.37,2012

In [13]:
filtered_columns3 = filtered_neighborhoods3[['Neighborhood 3', 'Building Classification 3', 'Total Units 3', 'Year Built 3', 'Estimated Gross Income 3', 'Estimated Expense 3']]
filtered_columns3.sample(10)

,Neighborhood 3,Building Classification 3,Total Units 3,Year Built 3,Estimated Gross Income 3,Estimated Expense 3
2379,MORRISANIA/LONGWOOD,C1 -WALK-UP,21,1905.0,"297,184","209,384"
16147,MORRISANIA/LONGWOOD,D6-ELEVATOR,187,1982.0,"2,332,193","1,348,788"
2445,MORRISANIA/LONGWOOD,C1 -WALK-UP,11,1904.0,"173,520","91,296"
16206,HUNTS POINT,C1-WALK-UP,46,1920.0,"371,807","234,731"
25727,MORRISANIA/LONGWOOD,C1-WALK-UP,30,1907.0,"290,845","166,102"
16201,HUNTS POINT,C1-WALK-UP,25,1922.0,"232,763","147,170"
6838,MORRISANIA/LONGWOOD,D1 -ELEVATOR,100,2003.0,"1,907,548","1,042,156"
16214,MORRISANIA/LONGWOOD,C1-WALK-UP,58,1910.0,"312,370","207,367"
2447,MORRISANIA/LONGWOOD,C1 -WALK-UP,16,1910.0,"195,410","106,450"
38665,MORRISANIA/LONGWOOD,D1-ELEVATOR,80,2012.0,"1,207,956","824,968"

In [16]:
filtered_columns3['Neighborhood 3'].value_counts()

Neighborhood 3
MORRISANIA/LONGWOOD       436
CROTONA PARK               53
HUNTS POINT                48
MOTT HAVEN/PORT MORRIS     26
Name: count, dtype: int64